{FEATURE} - Feature update /code clean for update 1.9
Foxlider/FASTER pull request #149
Opened 2023-10-13 12:39 UTC by jupster

Note I attend to use this as a beta until current update 1.9 comes out so If you aren't prepared to merge this for a while that is okay. 
## Description

Added code from @TheSpartaPT for optional mods in https://github.com/Foxlider/FASTER/pull/95 plus added their code from https://github.com/Foxlider/FASTER/pull/96 which adds me being less scared ill hit 'Delete All' by accident, plus a few other things.

Any feel free to add comments.
## Motivation and Context

Closes https://github.com/Foxlider/FASTER/pull/140
Closes https://github.com/Foxlider/FASTER/pull/138
Closes https://github.com/Foxlider/FASTER/pull/95
Closes https://github.com/Foxlider/FASTER/pull/96
Closes https://github.com/Foxlider/FASTER/issues/24
(Already added in 1.9 but cleaned code up) https://github.com/Foxlider/FASTER/pull/129
Closes https://github.com/Foxlider/FASTER/issues/144
Closes https://github.com/Foxlider/FASTER/issues/107
## How Has This Been Tested?

This has been tested to the best of my ability. The build is being run on a couple of servers successfully at this time. All build's working as expecting, the only think i think may be off is spacing but ill likely fix it later on. Not a major priority. Only issues i had run into was with 144 not working. It seems to be working flawlessly now.
## Screenshots (if appropriate):

## Types of changes

- [X] New feature (non-breaking change which adds functionality)
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [X] My code follows the code style of this project.
- [X] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-10-19 17:17 UTC, Foxlider requested changes
Not compiling, missing `}`

2023-10-19 17:17 UTC, Foxlider commented on FASTER/ViewModel/ModsViewModel.cs
> +            });
Missing }

2023-11-01 09:55 UTC, jupster commented
[Updated as it was 2 commits behind](https://github.com/jupster/FASTER/releases/tag/1.9d_142_beta)

2023-11-16 07:21 UTC, jupster commented
@Foxlider any chance we can get this reviewed so we it can be merged to Update 1.9. 

Thanks

2023-11-16 07:22 UTC, Foxlider commented
I got a week of exams but this weekend I'll look at it

2023-11-17 07:54 UTC, Foxlider approved these changes
awyep

2023-11-17 07:54 UTC, merged